package com.tuiken.royaladmin.model.enums;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public enum House {

    TUDOR("Tudor"),
    WINDSOR("Windsor"),
    SAXE_COBURG_AND_GOTHA("Saxe-Coburg and Gotha"),
    HANOVER("Hanover"),
    STUART("Stuart"),
    ORANGE_NASSAU("Orange-Nassau"),
    GREY("Grey"),
    YORK("York"),
    LANCASTER("Lancaster"),
    PLANTAGENET("Plantagenet"),
    ANGEVIN("Angevin"),
    BLOIS("Blois"),
    NORMANDY("Normandy"),
    GODWIN("Godwin"),
    WESSEX("Wessex"),
    KNYTLINGA("Knýtlinga"),
    SAXE_COBURG_SAALFELD("Saxe-Coburg-Saalfeld"),
    GLUCKSBURG("Glücksburg"),
    BERNADOTTE("Bernadotte"),
    HOLSTEIN_GOTTORP("Holstein-Gottorp"),
    OLDENBURG("Oldenburg"),
    BONDE("Bonde"),
    PALATINATE_NEUMARKT("Palatinate-Neumarkt"),
    GRIFFIN("Griffin"),
    ESTRIDSEN("Estridsen"),
    BJELBO("Bjelbo"), //
    SVERRE("Sverre"),
    GILLE("Gille"),
    HARDRADA("Hardrada"),
    FAIRHAIR("Fairhair"),
    ST_OLAF("St. Olaf"),
    BELGUIM("Belgium"),
    HESSE_KASSEL("Hesse-Kassel"),
    PALATINATE_ZWEIBRUCKEN("Palatinate-Zweibrücken"),
    VASA("Vasa"),
    MECKLENBURG_SCHWERIN("Mecklenburg-Schwerin"),
    ERIC("Eric"),
    SVERKER("Sverker"),
    STENKIL("Stenkil"),
    BOURBON("Bourbon"),
    SAVOY("Savoy"),
    HABSBURG("Habsburg"),
    HABSBURG_LORRAINE("Habsburg-Lorraine"),
    LORRAINE("Lorraine"),
    WITTELSBACH("Wittelsbach"),
    LUXEMBOURG("Luxembourg"),
    HOCHENSTAUFEN("Hohenstaufen"),
    WELF("Welf"),
    SUPPLINBURG("Supplinburg"),
    SALIAN("Salian"),
    OTTONIAN("Ottonian"),
    AMSBERG("Amsberg"),
    RUFFO_DI_CALABRIA("Ruffo di Calabria"),
    TECK("Teck"),
    PALATINATE_SIMMERN("Palatinate-Simmern"),
    NEVILLE("Neville"),
    CAPET("Capet"),
    TAILLEFER("Taillefer"),
    RAMNULFIDS("Ramnulfids"),
    FLANDERS("Flanders"),
    RURIK("Rurik"),
    HOHENZOLLERN_SIGMARINGEN("Hohenzollern-Sigmaringen"),
    REUSS("Reuss"),
    ORLEANS("Orléans"),
    BRAGANZA("Braganza"),
    AVIZ("Aviz"),
    SAXE_GOTHA_ALTENBURG("Saxe-Gotha-Altenburg"),
    SEYMOUR("Seymour"),
    IVREA("Ivrea"),
    MECKLENBURG_STRELITZ("Mecklenburg-Strelitz"),
    JELLING("Jelling"),
    GORM("Gorm"),
    BARCELONA("Barcelona"),
    WETTIN("Wettin"),
    VALOIS("Valois"),
    FARNESE("Farnese"),
    BURGUNDY("Burgundy"),
    TRASTAMARA("Trastámara"),
    BONAPARTE("Bonaparte"),
    MEDICI("Medici"),
    PORTUGUESE_BURGUNDY("Portuguese Burgundy"),
    HOHENZOLLERN("Hohenzollern"),
    AVIS("Avis"),
    MENESES("Meneses"),
    CAROLINGIAN("Carolingian"),
    BIVINIDS("Bivinids"),
    HESSE_DARMSTADT("Hesse-Darmstadt"),
    JAGIELLON("Jagiellon"),
    SAXE_WEIMAR_EISENACH("Saxe-Weimar-Eisenach"),
    ASCANIA("Ascania"),
    OLAF("Olaf"),
    SOBIESKI("Sobieski"),
    NASSAU_WEILBURG("Nassau-Weilburg"),
    SCHLESWIG_HOLSTEIN_SONDERBURG_AUGUSTENBURG("Schleswig-Holstein-Sonderburg-Augustenburg"),
    ERIK("Erik"),
    PIAST("Piast"),
    DAMPIERRE("Dampierre"),
    ALBA_DE_TORMES("Alba de Tormes"),
    HAUTEVILLE("Hauteville"),
    KETTELER("Ketteler"),
    AUSTRIA_ESTE("Austria-Este"),
    NORMAN("Norman"),
    CONRADINES("Conradines"),
    GUELPH("Guelph"),
    SCHAUENBURG("Schauenburg"),
    LIPPE_BIESTERFELD("Lippe-Biesterfeld"),
    BEAUHARNAIS("Beauharnais"),
    ROBERTIAN("Robertian"),
    MECKLENBURG("Mecklenburg"),
    MEDINA_SIDONIA("Medina Sidonia"),
    BOURBON_TWO_SICILIES("Bourbon-Two Sicilies"),
    JIMENES("Jiménez"),
    PONIATOWSKI("Poniatowski"),
    WISNOWIECKI("Wiśniowiecki"),
    LESZCZINSKY("Leszczyński"),
    ANJOU("Anjou"),
    PREMYSLID("Přemyslid"),
    STEWART("Stewart"),
    BRUCE("Bruce"),
    EGMOND("Egmond"),
    PREMYSLOVCI("Přemyslovci"),
    ARAGON("Aragon"),
    LEININGEN("Leiningen"),
    LESZCZYNSKI("Leszczyński"),
    WURTTEMBERG("Württemberg"),
    BATTENBERG("Battenberg"),
    PALATINE_SIMMERN("Palatine-Simmern"),
    POITIERS("Poitiers"),
    BRUNSWICK_BEVERN("Brunswick-Bevern"),
    GERULFING("Gerulfing"),
    HOLSTEIN_GOTTORP_ROMANOV("Holstein-Gottorp-Romanov"),
    BEAUFORT("Beaufort"),
    GONZAGA("Gonzaga"),
    SOLMS_BRAUNFELS("Solms-Braunfels"),
    CRAMM("Cramm"),
    KETTLER("Kettler"),
    CELJE("Celje"),
    SVIATOSLAVICHI("Sviatoslavichi"),
    NAKONIDS("Nakonids"),
    NASSAU("Nassau"),
    BRIENNE("Brienne"),
    SFORZA("Sforza"),
    COURTENAY("Courtenay"),
    SAYN_WITTGENSTEIN_BERLEBURG("Sayn-Wittgenstein-Berleburg"),
    GEDIMINIDS("Gediminids"),
    OLGOVICHI("Olgovichi"),
    BURGH("Burgh"),
    MORAY("Moray"),
    SAXE_MEININGEN("Saxe-Meiningen"),
    AVESNES("Avesnes"),
    COUCY("Coucy"),
    REGINAR("Reginar"),
    SCHWARZBURG_RUDOLSTADT("Schwarzburg-Rudolstadt"),
    BALLIOL("Balliol"),
    ETICHONIDS("Etichonids"),
    MONTDIDIER("Montdidier"),
    BOSO("Boso"),
    ESTE("Este"),
    DUNKELD("Dunkeld"),
    EZZONEN("Ezzonen"),
    TORLONIA("Torlonia"),
    DREUX("Dreux"),
    SAXE_HILDBURGHAUSEN("Saxe-Hildburghausen"),
    ALPIN("Alpin"),
    HOHENZOLLOERN("Hohenzolloern"),
    GUISE("Guise"),
    HOHENBERG("Hohenberg"),
    ALBRET("Albret"),
    ABERFFRAW("Aberffraw"),
    LIPPE("Lippe"),
    BILLUNG("Billung"),
    DREUX_MONTFORT("Dreux-Montfort"),
    KOMNENODOUKAI("Komnenodoukai"),
    GORIZIA("Gorizia"),
    UDALRICHING("Udalriching"),
    ROMANOV("Romanov"),
    GEDIMINID("Gediminid"),
    ALERAMICI("Aleramici"),
    ROUERGUE("Rouergue"),
    HESSE("Hesse"),
    RENNES("Rennes"),
    HOHENSTAUFEN("Hohenstaufen"),
    DENMARK("Denmark"),
    ANJOU_SICILY("Anjou-Sicily"),
    AHLEFELDT("Ahlefeldt"),
    BOSONIDS("Bosonids"),
    SCHLESWIG_HOLSTEIN_SONDERBURG("Schleswig-Holstein-Sonderburg"),
    GEDIMINAS("Gediminas"),
    MORTIMER("Mortimer"),
    BABENBERG("Babenberg"),
    RETHEL("Rethel"),
    ARPAD("Árpád"),
    HUNYADI("Hunyadi"),
    LASKARIS("Laskaris"),
    VERGY("Vergy"),
    LIECHTENSTEIN("Liechtenstein"),
    ZAHRINGEN("Zähringen"),
    SHUYSKY("Shuysky"),
    CZARTORYSKI("Czartoryski"),
    SRATSIMIR("Sratsimir"),
    SHISHMAN("Shishman"),
    TERTER("Terter"),
    BORJIGIN("Borjigin"),
    ASEN("Asen"),
    ENRIQUEZ("Enríquez"),
    BIRON("Biron"),
    MOUNTBATTEN("Mountbatten"),
    HUGEL("Hügel"),
    GRIMALDI("Grimaldi"),
    POLIGNAC("Polignac"),
    MERODE("Merode");

    private final String label;

    House(String label) {
        this.label = label;
    }

    public static House HouseFromBeginningOfString(String src) {
        for (House h : House.values()) {
            if (src.toUpperCase().startsWith(h.label.toUpperCase())) {
                return h;
            }
        }
        if (!src.toUpperCase().contains("HOUSE") && !src.toUpperCase().contains("AGNATIC")) {
            log.info("!!!!! ==== House detection ===== !!!!!!\nUnrecognized: " + src);
        }
        return null;
    }

}
