package com.tuiken.royaladmin.model.enums;

import lombok.extern.slf4j.Slf4j;

import java.io.FileWriter;
import java.io.IOException;

@Slf4j
public enum House {
    TUDOR("Tudor"),
    WINDSOR("Windsor"),
    SAXE_COBURG_AND_GOTHA("Saxe-Coburg and Gotha"),
    SAXE_COBURG("Saxe-Coburg"),
    HANOVER("Hanover"),
    STUART("Stuart"),
    ORANGE_NASSAU("Orange-Nassau"),
    GREY("Grey"),
    YORK("York"),
    LANCASTER("Lancaster"),
    PLANTAGENET("Plantagenet"),
    ANGEVIN("Angevin"),
    BLOIS("Blois"),
    NORMANDY("Normandy"),
    GODWIN("Godwin"),
    WESSEX("Wessex"),
    KNYTLINGA("Knýtlinga"),
    SAXE_COBURG_SAALFELD("Saxe-Coburg-Saalfeld"),
    GLUCKSBURG("Glücksburg"),
    BERNADOTTE("Bernadotte"),
    HOLSTEIN_GOTTORP("Holstein-Gottorp"),
    OLDENBURG("Oldenburg"),
    BONDE("Bonde"),
    PALATINATE_NEUMARKT("Palatinate-Neumarkt"),
    GRIFFIN("Griffin"),
    ESTRIDSEN("Estridsen"),
    BJELBO("Bjelbo"), //
    SVERRE("Sverre"),
    GILLE("Gille"),
    HARDRADA("Hardrada"),
    FAIRHAIR("Fairhair"),
    ST_OLAF("St. Olaf"),
    BELGUIM("Belgium"),
    HESSE_KASSEL("Hesse-Kassel"),
    PALATINATE_ZWEIBRUCKEN("Palatinate-Zweibrücken"),
    VASA("Vasa"),
    MECKLENBURG_SCHWERIN("Mecklenburg-Schwerin"),
    ERIC("Eric"),
    SVERKER("Sverker"),
    STENKIL("Stenkil"),
    BOURBON("Bourbon"),
    SAVOY("Savoy"),
    HABSBURG("Habsburg"),
    HABSBURG_LORRAINE("Habsburg-Lorraine"),
    LORRAINE("Lorraine"),
    WITTELSBACH("Wittelsbach"),
    LUXEMBOURG("Luxembourg"),
    HOCHENSTAUFEN("Hohenstaufen"),
    WELF("Welf"),
    SUPPLINBURG("Supplinburg"),
    SALIAN("Salian"),
    OTTONIAN("Ottonian"),
    AMSBERG("Amsberg"),
    RUFFO_DI_CALABRIA("Ruffo di Calabria"),
    TECK("Teck"),
    PALATINATE_SIMMERN("Palatinate-Simmern"),
    NEVILLE("Neville"),
    CAPET("Capet"),
    TAILLEFER("Taillefer"),
    RAMNULFIDS("Ramnulfids"),
    FLANDERS("Flanders"),
    RURIK("Rurik"),
    HOHENZOLLERN_SIGMARINGEN("Hohenzollern-Sigmaringen"),
    REUSS("Reuss"),
    ORLEANS("Orléans"),
    BRAGANZA("Braganza"),
    AVIZ("Aviz"),
    SAXE_GOTHA_ALTENBURG("Saxe-Gotha-Altenburg"),
    SEYMOUR("Seymour"),
    IVREA("Ivrea"),
    MECKLENBURG_STRELITZ("Mecklenburg-Strelitz"),
    JELLING("Jelling"),
    GORM("Gorm"),
    BARCELONA("Barcelona"),
    WETTIN("Wettin"),
    VALOIS("Valois"),
    FARNESE("Farnese"),
    BURGUNDY("Burgundy"),
    TRASTAMARA("Trastámara"),
    BONAPARTE("Bonaparte"),
    MEDICI("Medici"),
    PORTUGUESE_BURGUNDY("Portuguese Burgundy"),
    HOHENZOLLERN("Hohenzollern"),
    AVIS("Avis"),
    MENESES("Meneses"),
    CAROLINGIAN("Carolingian"),
    BIVINIDS("Bivinids"),
    HESSE_DARMSTADT("Hesse-Darmstadt"),
    JAGIELLON("Jagiellon"),
    SAXE_WEIMAR_EISENACH("Saxe-Weimar-Eisenach"),
    ASCANIA("Ascania"),
    OLAF("Olaf"),
    SOBIESKI("Sobieski"),
    NASSAU_WEILBURG("Nassau-Weilburg"),
    SCHLESWIG_HOLSTEIN_SONDERBURG_AUGUSTENBURG("Schleswig-Holstein-Sonderburg-Augustenburg"),
    ERIK("Erik"),
    PIAST("Piast"),
    DAMPIERRE("Dampierre"),
    ALBA_DE_TORMES("Alba de Tormes"),
    HAUTEVILLE("Hauteville"),
    KETTELER("Ketteler"),
    AUSTRIA_ESTE("Austria-Este"),
    NORMAN("Norman"),
    CONRADINES("Conradines"),
    GUELPH("Guelph"),
    SCHAUENBURG("Schauenburg"),
    LIPPE_BIESTERFELD("Lippe-Biesterfeld"),
    BEAUHARNAIS("Beauharnais"),
    ROBERTIAN("Robertian"),
    MECKLENBURG("Mecklenburg"),
    MEDINA_SIDONIA("Medina Sidonia"),
    BOURBON_TWO_SICILIES("Bourbon-Two Sicilies"),
    JIMENES("Jiménez"),
    PONIATOWSKI("Poniatowski"),
    WISNOWIECKI("Wiśniowiecki"),
    LESZCZINSKY("Leszczyński"),
    ANJOU("Anjou"),
    PREMYSLID("Přemyslid"),
    STEWART("Stewart"),
    BRUCE("Bruce"),
    EGMOND("Egmond"),
    PREMYSLOVCI("Přemyslovci"),
    ARAGON("Aragon"),
    LEININGEN("Leiningen"),
    LESZCZYNSKI("Leszczyński"),
    WURTTEMBERG("Württemberg"),
    BATTENBERG("Battenberg"),
    PALATINE_SIMMERN("Palatine-Simmern"),
    POITIERS("Poitiers"),
    BRUNSWICK_BEVERN("Brunswick-Bevern"),
    GERULFING("Gerulfing"),
    HOLSTEIN_GOTTORP_ROMANOV("Holstein-Gottorp-Romanov"),
    BEAUFORT("Beaufort"),
    GONZAGA("Gonzaga"),
    SOLMS_BRAUNFELS("Solms-Braunfels"),
    CRAMM("Cramm"),
    KETTLER("Kettler"),
    CELJE("Celje"),
    SVIATOSLAVICHI("Sviatoslavichi"),
    NAKONIDS("Nakonids"),
    NASSAU("Nassau"),
    BRIENNE("Brienne"),
    SFORZA("Sforza"),
    COURTENAY("Courtenay"),
    SAYN_WITTGENSTEIN_BERLEBURG("Sayn-Wittgenstein-Berleburg"),
    GEDIMINIDS("Gediminids"),
    OLGOVICHI("Olgovichi"),
    BURGH("Burgh"),
    MORAY("Moray"),
    SAXE_MEININGEN("Saxe-Meiningen"),
    AVESNES("Avesnes"),
    COUCY("Coucy"),
    REGINAR("Reginar"),
    SCHWARZBURG_RUDOLSTADT("Schwarzburg-Rudolstadt"),
    BALLIOL("Balliol"),
    ETICHONIDS("Etichonids"),
    MONTDIDIER("Montdidier"),
    BOSO("Boso"),
    ESTE("Este"),
    DUNKELD("Dunkeld"),
    EZZONEN("Ezzonen"),
    TORLONIA("Torlonia"),
    DREUX("Dreux"),
    SAXE_HILDBURGHAUSEN("Saxe-Hildburghausen"),
    ALPIN("Alpin"),
    HOHENZOLLOERN("Hohenzolloern"),
    GUISE("Guise"),
    HOHENBERG("Hohenberg"),
    ALBRET("Albret"),
    ABERFFRAW("Aberffraw"),
    LIPPE("Lippe"),
    BILLUNG("Billung"),
    DREUX_MONTFORT("Dreux-Montfort"),
    KOMNENODOUKAI("Komnenodoukai"),
    GORIZIA("Gorizia"),
    UDALRICHING("Udalriching"),
    ROMANOV("Romanov"),
    GEDIMINID("Gediminid"),
    ALERAMICI("Aleramici"),
    ROUERGUE("Rouergue"),
    HESSE("Hesse"),
    RENNES("Rennes"),
    HOHENSTAUFEN("Hohenstaufen"),
    DENMARK("Denmark"),
    ANJOU_SICILY("Anjou-Sicily"),
    AHLEFELDT("Ahlefeldt"),
    BOSONIDS("Bosonids"),
    SCHLESWIG_HOLSTEIN_SONDERBURG("Schleswig-Holstein-Sonderburg"),
    GEDIMINAS("Gediminas"),
    MORTIMER("Mortimer"),
    BABENBERG("Babenberg"),
    RETHEL("Rethel"),
    ARPAD("Árpád"),
    HUNYADI("Hunyadi"),
    LASKARIS("Laskaris"),
    VERGY("Vergy"),
    LIECHTENSTEIN("Liechtenstein"),
    ZAHRINGEN("Zähringen"),
    SHUYSKY("Shuysky"),
    CZARTORYSKI("Czartoryski"),
    SRATSIMIR("Sratsimir"),
    SHISHMAN("Shishman"),
    TERTER("Terter"),
    BORJIGIN("Borjigin"),
    ASEN("Asen"),
    ENRIQUEZ("Enríquez"),
    BIRON("Biron"),
    MOUNTBATTEN("Mountbatten"),
    HUGEL("Hügel"),
    GRIMALDI("Grimaldi"),
    POLIGNAC("Polignac"),
    MERODE("Merode"),
    MUNSO("Munsö"),
    KARADORDEVIC("Karađorđević"),
    VATATZES("Vatatzes"),
    ANGELOS("Angelos"),
    NEMANJIC("Nemanjić"),
    HASHEMITE("Hashemite"),
    CHERNYSHYEV_BESOBRASOV("Chernyshyev-Besobrasov"),
    METZ("Metz"),
    LA_MARCK("La Marck"),
    SPONHEIM("Sponheim"),
    WELSER("Welser"),
    PALAEOLOGUS_MONTFERRAT("Palaeologus-Montferrat"),
    URACH("Urach"),
    SILESIAN_PIASTS("Silesian Piasts"),
    LUDOVINGIANS("Ludovingians"),
    BJALBO("Bjälbo"),
    WIZLAW("Wizlaw"),
    VISCONTI("Visconti"),
    THURN_TAXIS("Thurn and Taxis"),
    LA_CERDA("la Cerda"),
    MUKHRANI("Mukhrani"),
    BAGRATIONI_MUKHRANELI("Bagrationi-Mukhraneli"),
    PETROVIC_NJEGOS("Petrović-Njegoš"),
    ZAMOYSKI("Zamoyski"),
    ROCHECHOUART("Rochechouart"),
    WURTTEMBURG("Württemburg"),
    BURKE("Burke"),
    NEIPPERG_MONTENUOVO("Neipperg-Montenuovo"),
    KOMNENIAN("Komnenian"),
    CLAN_MAR("Clan Mar"),
    ROBERTIANS("Robertians"),
    JABLONOWSKI("Jabłonowski"),
    JIMENEZ("Jiménez"),
    RADZIWILL("Radziwiłł"),
    WIED_NEUWIED("Wied-Neuwied"),
    VON_WARTENSLEBEN("von Wartensleben"),
    BRUNONIDS("Brunonids"),
    CLAN_DRUMMOND("Clan Drummond"),
    ARENBERG("Arenberg"),
    DE_WARENNE("de Warenne"),
    SALM("Salm"),
    MONTOIRE("Montoire"),
    WALDECK("Waldeck"),
    ARMAGNAC("Armagnac"),
    DIETRICHSTEIN("Dietrichstein"),
    LA_TREMOILLE("La Trémoille"),
    EKA("Eka"),
    KOTROMANIC("Kotromanić"),
    MONTFORT_BRITANNY("Montfort-Britanny"),
    UNRUOCHING("Unruoching"),
    CZARNKOWSKI("Czarnkowski"),
    GISONES("Gisones"),
    HARCOURT("Harcourt"),
    WINDISCH_GRAETZ("Windisch-Graetz"),
    BUONAPARTE("Buonaparte"),
    BADEN("Baden"),
    DE_LA_CERDA("House de la Cerda"),
    WOLFSTEIN("Wolfstein"),
    LOWENSTEIN_WERTHEIM("Löwenstein-Wertheim"),
    DELLA_ROVERE("della Rovere"),
    WISNIOWIECKI("Wiśniowiecki"),
    OLDENBORG("Oldenborg"),
    ZARINGEN("Zähringen"),
    TILNEY("Tilney"),
    TURUL("Turul"),
    THOPIA("Thopia"),
    VINSTORPA("Vinstorpa"),
    HOHENLOHE_LANGENBURG("Hohenlohe-Langenburg"),
    AUMONT("Aumont"),
    MONTBELIARD("Montbéliard"),
    VALOIS_ORLÉANS("Valois-Orléans"),
    ENGHIEN("Enghien"),
    ZACCARIA("Zaccaria"),
    FOIX_GRAILLY("Foix-Grailly"),
    CYBO_MALASPINA("Cybo-Malaspina"),
    SABRAN("Sabran"),
    WARENNE("Warenne"),
    FLAHAUT("Flahaut"),
    BEAUCLERK("Beauclerk"),
    ARDUINICI("Arduinici"),
    TERTEROBA("Terteroba"),
    ALSACE("Alsace"),
    SCHLESWIG_HOLSTEIN_SONDERBURG_BECK("Schleswig-Holstein-Sonderburg-Beck"),
    ALPINID("Alpínid"),
    L_AIGLE("L\"Aigle"),
    KOMNENOS("Komnenos"),
    BORGIA("Borgia"),
    ARAGÓN("Aragón"),
    SCHAUMBURG_LIPPE("Schaumburg-Lippe"),
    HOWARD("Howard"),
    FITZALAN("FitzAlan"),
    CAPETIAN_COURTENAY("Capetian  Courtenay"),
    CASTELLANE("Castellane"),
    BRUNONEN("Brunonen"),
    MURAT("Murat"),
    LAVAL("Laval"),
    DOUGLAS("Douglas"),
    EGMONT("Egmont"),
    SMILETS("Smilets"),
    BETHUNE("Bethune"),
    AHALOLFINGS("Ahalolfings"),
    CASTILIAN_IVREA("Castilian Ivrea"),
    SUPPLINBURGER("Supplinburger"),
    ARDENNES_METZ("Ardennes-Metz"),
    INGELGER("Ingelger"),
    BASARAB("Basarab"),
    ELDER_WELF("Elder  Welf"),
    CONRADINE("Conradine"),
    NAMUR("Namur"),
    MONTENUOVO("Montenuovo"),
    OETTINGEN_OETTINGEN("Oettingen-Oettingen"),
    DE_CLARE("de Clare"),
    LANNOY("Lannoy"),
    KINSKY("Kinsky"),
    LIMBURG("Limburg"),
    MERENBERG("Merenberg"),
    OSTROGSKI("Ostrogski"),
    DEJANOVIC("Dejanović"),
    ALBERT("Albert"),
    ARDENNES_VERDUN("Ardennes-Verdun"),
    CORNARO("Cornaro"),
    DINEFWR("Dinefwr"),
    LIGNE("Ligne"),
    NARYSHKIN("Naryshkin"),
    CLAN_SETON("Clan Seton"),
    KOMNENODOUKAS("Komnenodoukas"),
    ARTOIS("Artois"),
    SCALIGER("Scaliger"),
    HAMILTON("Hamilton"),
    KAZANOWSKI("Kazanowski"),
    ZAPOLYA("Zápolya"),
    SISMAN("Šišman"),
    AYALA("Ayala"),
    EMBRIACO("Embriaco"),
    MOROSINI("Morosini"),
    CHATILLON("Châtillon"),
    BIGOD("Bigod"),
    HOUSE_DALBERT("House d\"Albert"),
    DE_VERE("De Vere"),
    HOHENZOLERN("Hohenzolern"),
    MONTFORT_BRITTANY("Montfort-Brittany"),
    BELLEME("Bellême"),
    DOUKAS("Doukas"),
    TASCHER_DE_LA_PAGERIE("Tascher de La Pagerie"),
    SCHLESWIG_HOLSTEIN_GLUCKSBURG("Schleswig-Holstein-Glücksburg"),
    SALVIATI("Salviati"),
    MARSHAL("Marshal"),
    CASTRO("Castro"),
    LOPUKHIN("Lopukhin"),
    CLAN_GORDON("Clan Gordon"),
    CHURCHILL("Churchill"),
    ARDENNE_BAR("Ardenne–Bar"),
    KANTAKOUZENOS("Kantakouzenos"),
    YURYEVSKY("Yuryevsky"),
    ORSINI("Orsini"),
    GODUNOV("Godunov"),
    ORSEOLO("Orseolo"),
    TALLEYRAND_PÉRIGORD("Talleyrand-Périgord"),
    BRANDENBURG_SCHWEDT("Brandenburg-Schwedt"),
    HUNFRIDINGS("Hunfridings"),
    DUDEKEM_DACOZ("d\"Udekem d\"Acoz"),
    MORSZTYN("Morsztyn"),
    CLAN_MACDUFF("Clan MacDuff"),
    CHALON_ARLAY("Chalon-Arlay"),
    NOAILLES("Noailles"),
    FURSTENBERG_WEITRA("Fürstenberg-Weitra"),
    DANNESKIOLD_SAMSOE("Danneskiold-Samsøe"),
    STEWART_OF_DARNLEY("Stewart of Darnley"),
    LARA("Lara"),
    BOHUN("Bohun"),
    BRANKOVIC("Branković"),
    PENTHIEVRE("Penthièvre"),
    LOWENSTEIN_WERTHEIM_ROSENBERG("Löwenstein-Wertheim-Rosenberg"),
    EZZONIDS("Ezzonids"),
    FITZCLARENCE("FitzClarence"),
    SOLMS_LAUBACH("Solms-Laubach"),
    HANAU_SCHAUMBURG("Hanau-Schaumburg"),
    PALAIOLOGOS("Palaiologos"),
    LA_TOUR_DAUVERGNE("La Tour d\"Auvergne"),
    FITZJAMES("FitzJames"),
    ROUPENIANS("Roupenians"),
    BOLEYN("Boleyn"),
    OENGUS("Óengus"),
    BOWES_LYON("Bowes-Lyon"),
    IBELIN("Ibelin"),
    PODEBRADY("Poděbrady"),
    COMMINGES("Comminges"),
    MONTAGU_DOUGLAS_SCOTT("Montagu Douglas Scott"),
    DOLGORUKOV("Dolgorukov"),
    MEINHARDINER("Meinhardiner"),
    THURN_AND_TAXIS("Thurn and Taxis"),
    BOULOGNE("Boulogne"),
    DELLA_SCALA("della Scala"),
    ERBACH("Erbach"),
    MONTFORT("Montfort"),
    COLIGNY("Coligny"),
    STOLBERG("Stolberg"),
    PARDAILLAN("Pardaillan"),
    VUKANOVIC("Vukanović"),
    BANER("Banér"),
    KESTUTIS("Kęstutis"),
    LUITPOLDINGS("Luitpoldings"),
    UNRUOCHINGS("Unruochings"),
    PETRALIPHAS("Petraliphas"),
    STERNBERG("Sternberg"),
    GISKEAETTEN("Giskeætten"),
    OSTROROG("Ostroróg"),
    KOMNENOS_DOUKAS("Komnenos Doukas"),
    CLAN_BRUCE("Clan Bruce"),
    VALOIS_ANGOULEME("Valois-Angoulême"),
    CILLI("Cilli"),
    DE_BRIENNE("de Brienne"),
    OPALINSKI("Opaliński"),
    KOHARY("Koháry"),
    YNGLING("Yngling"),
    MERODE_WESTERLOO("Mérode-Westerloo"),
    BAUX("Baux"),
    SZILAGYI("Szilágyi"),
    DE_LA_POLE("de la Pole"),
    FURSTENBERG("Fürstenberg"),
    YURIEVICHI("Yurievichi"),
    GRAMONT("Gramont"),
    DENTUMOGER("Dentumoger"),
    SAXE_ALTENBURG("Saxe-Altenburg"),
    ABBADID("Abbadid"),
    ASTUR_LEONESE("Astur-Leonese"),
    MONOMAKHOVICHI("Monomakhovichi"),
    CHATENOIS("Châtenois"),
    HETHUMID("Hethumid"),
    MALATESTA("Malatesta"),
    TOULOUSE("Toulouse"),
    AUVERGNE("Auvergne"),
    GYULA_LINEAGE("Gyula lineage"),
    ROHAN("Rohan"),
    ANDECHS("Andechs"),
    CIRKSENA("Cirksena"),
    BEAUCHAMP("Beauchamp"),
    JULICH("Jülich"),
    EVREUX("Évreux"),
    LUSIGNAN("Lusignan"),
    HOLLAND("Holland"),
    OETTINGEN("Oettingen"),
    SCHWARZBURG("Schwarzburg"),
    CHAVCHAVADZE("Chavchavadze"),
    FOIX_CANDALE("Foix-Candale"),
    FOIX("Foix"),
    THOUARS("Thouars"),
    FRIAS("Frías"),
    KOSTKA("Kostka"),
    VIZLAV("Vizlav"),
    BRANDON("Brandon"),
    DELA_FLECHE_DE_BAUGENCY("de La Flèche-de Baugency"),
    POTOCKI("Potocki"),
    OBRENOVIC("Obrenović");

    private static final String UNSAVED_HOUSES_FILE = "C:\\Users\\MT\\IdeaProjects\\royal_admin\\data\\houses.txt";
    private final String label;

    House(String label) {
        this.label = label;
    }

    public static House HouseFromBeginningOfString(String src) {
        for (House h : House.values()) {
            if (src.toUpperCase().startsWith(h.label.toUpperCase())) {
                return h;
            }
        }
        if (!src.toUpperCase().contains("HOUSE") && !src.toUpperCase().contains("AGNATIC")) {
            log.info("!!!!! ==== House detection ===== !!!!!!\nUnrecognized: " + src);
            FileWriter writer = null; // true for append mode
            try {
                writer = new FileWriter(UNSAVED_HOUSES_FILE, true);
                writer.write(String.format("%s(\"%s\"),\n", src.toUpperCase(), src));
                writer.close();
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        }
        return null;
    }

}
